### ISSUE TITLE
Large coordinates are not returned exactly, because of conversion to floats

### ISSUE THREAD

**Issue by Feuermurmel** [greginvm/pyclipper#2]
I've noticed that the coordinates of the paths returned by `pyclipper.Execute()` are represented using floats. This introduces some inaccuracies for very large coordinate values as not all values of an `int64_t` can be represented by a `double`. I've added a test case here showing the problem:

https://github.com/Feuermurmel/pyclipper/tree/inexact-coordinates

I see that the library supports automatic scaling of coordinate values by setting the global `pyclipper.SCALING_FACTOR`. This of course means that, unless this variable is set to 1, a type other than `int` is necessary to represent coordinates. Thus I'm not sure what the best way is to solve this problem. I currently see the following options:

– Remove `pyclipper.SCALING_FACTOR`, but there are probably some people using it.
– Only use floats when `pyclipper.SCALING_FACTOR` is not set to 1. Seems a bit hack-ish.
– Add a second implementation of `pyclipper.Pyclipper` which ignores the scaling factor and uses ints instead. This seems obscure and bloats the library.

**Comment by greginvm** [comment]
I think the correct way to do this is to deprecate the `SCALING_FACTOR` and deal with integers in a new version and provide a workaround for those users that do use it (eg. a separate function that does only this). This way wrapper does not mess with the numbers the base library provides.

Do you wan't to provide a PR that removes this? Otherwise I'll do it.

**Comment by Feuermurmel** [comment]
I'll try to work something up. I already have [a version](https://github.com/Feuermurmel/pyclipper/commit/a7ee89fa92a852d83e2025a115fcfa75cb2ddc67) with `SCALING_FACTOR`. I'll add some helper methods to scale coordinates and create a PR.

Is it ok to remove `SCALING_FACTOR` altogether, breaking code that uses it?

**Comment by greginvm** [comment]
I think the removal of the `SCALING_FACTOR` functionality is a must as it modifies the behavior of the underlying library. It would be a good idea though to leave the variable in the code, and warn users that it is deprecated if it is set to anything other than `1`. It would be nice if the warning message would contain a link to README here on GitHub where a workaround would be described (using the helper methods). 

The check for it could be placed in every function in the following fashion (if you have some other idea you are welcome to use it :)
```
def SimplifyPolygon(poly, PolyFillType fill_type=pftEvenOdd):
    ....
    _check_warnings()
   ...

def _check_warnings():
    if SCALING_FACTOR != 1:
        print "SCALING_FACTOR is deprecated, use #helper methods# or visit https://... for instructions on upgrading"

```

Thank you for your contribution!

**Comment by Feuermurmel** [comment]
@greginvm I've created a [pull request](#3). Can you have a look at it and see whether it's acceptable?

I've never worked with Cython before, so there's probably a lot of potential for stupid stuff I could have missed.

**Comment by greginvm** [comment]
@Feuermurmel Great! I've seen it, haven't had time to go through it thoroughly (will do that in the following days), but at first glance it looks very solid :+1: ! I especially like that you made tests for everything and the wiki page. 

About the version - the public API is changed and is not fully backwards compatible, so it would be a good idea to go to the next major version ([Semantic Versioning](http://semver.org/)). The next one is than `1.0.0`. Do you see any other needed change or fix that would be needed and could potentially break the API so that we could include it?

**Comment by Feuermurmel** [comment]
I have a few Ideas of for changes to the API that also would break backward compatibility, but I'm not sure which are worthwhile to implement. Maybe the most glaring part about the API is that it does not seem very _Pythonic_ to me.

For example, method names all start with a capital letter, which contradicts the convention in Python. I see that the API of Pyclipper has been structured to align very closely with that of Clipper, so maybe there's a benefit there. Also, IMHO, there should be two separate methods to add _subject_ and _clip_ paths/polygons, instead of passing an argument to select one or the other behavior.

But maybe providing an API which is more fitting for a Python environment is not the task of this library and should be left to other libraries built on top of Pyclipper.

What do you think?

**Comment by greginvm** [comment]
Hey,

yes, I know that it is not the most Pythonic, but as you said - this way it is more aligned with the base library and with its usage philosophy.

Thank you for your contribution!
