### ISSUE TITLE
pre-compiled wheels on PyPI?

### ISSUE THREAD

**Issue by anthrotype** [greginvm/pyclipper#4]
Hi @greginvm,

Thanks for the great package. I was wondering if you would be interested in setting up Travis and Appveyor CI to build wheel packages to be deployed on PyPI, alongside the current source distribution.

Being written in cython, the library is very portable and can be easily compiled on all platforms. However, a lot of users (especially Windows and Mac users) do not have easy access to a C++ compiler. It would be nice if they could just `pip install pyclipper` or if other higher-level libraries could simply specify `pyclipper` as a dependency, without worring about the dreaded `Unable to find vcvarsall.bat` error ;)

I can work on a pull request, but first wanted to check with you.
Thanks,

Cosimo

**Comment by anthrotype** [comment]
ping!

**Comment by greginvm** [comment]
Hi @anthrotype ,

it sounds like a great idea, I'll accept a PR. Do you think both are needed or would Appveyor be enough? I see that Travis is lacking Windows support, does it have anything that would be useful that Appveyor doesn't have?

Best,
Gregor

**Comment by anthrotype** [comment]
> Do you think both are needed or would Appveyor be enough?

Yeah, we need both if we want to support all three major operating systems. Appveyor only does Windows, wheres Travis does both Linux and OS X.

So I'll start working on a PR then ;)

**Comment by greginvm** [comment]
Hi @anthrotype , I uploaded the new version including wheels to PyPI. Thank you for preparing everything necessary for this to happen! :pizza: :beers: :fireworks:  I'll close this issue now as its done and in production.

**Comment by anthrotype** [comment]
Super! Thank you :)
